/**
 * seed-bikes.mjs
 * Run with: node scripts/seed-bikes.mjs
 * Inserts 14 electric bikes into MongoDB.
 */

import { MongoClient } from "mongodb";

const MONGODB_URI =
  "mongodb+srv://rahulwebdeveloper12_db_user:udPOmJd7tHBRNqmj@ev-vehicles.npunihy.mongodb.net/?appName=Ev-vehicles";
const DB_NAME = "Ev-vehicles";

/* ─── Seed data ─────────────────────────────────────────────────────── */
const bikes = [
  {
    name: "Ola S1 Pro",
    brand: "Ola Electric",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ola-s1-pro",
    status: "published",
    featured: true,
    shortDescription:
      "India's best-selling electric scooter with 195 km range, MoveOS, and hypercharging support.",
    videoUrl: "https://www.youtube.com/watch?v=MqMN0TRiMrk",
    variants: [
      {
        name: "S1 Pro Gen 2",
        exShowroomPrice: "₹1,29,999",
        onRoadPrice: "₹1,45,000",
        batteryCapacity: "4 kWh",
        range: "195 km",
        availabilityStatus: "Available",
        features: ["Hypercharger Support", "4G Connectivity", "Voice Assistant"],
      },
    ],
    performance: {
      batteryCapacity: "4 kWh",
      drivingRange: "195 km",
      power: "8.5 kW",
      peakPower: "11 kW",
      torque: "58 Nm",
      topSpeed: "120 km/h",
      acceleration: "3 sec (0–40 km/h)",
      driveType: "Rear Hub Drive",
      batteryType: "Lithium-Ion NMC",
    },
    charging: { acChargingTime: "6.5 hrs", dcChargingTime: "30 min (0–50%)", fastCharging: true, chargingPort: "CCS2" },
    specs: { length: "1859 mm", width: "712 mm", height: "1154 mm", wheelbase: "1350 mm", groundClearance: "165 mm", kerbWeight: "125 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: true, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" Touchscreen', "MoveOS 4", "Voice Assistant"], connectivity: ["4G LTE", "Bluetooth 5.0", "Wi-Fi"], comfort: ["Reverse Mode", "Hill Hold", "50L Under-Seat Storage"], technology: ["Geo-Fencing", "Trip Planning", "Theft Alert", "OTA Updates"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["Combined Braking System", "Find My Scooter"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Highest range in segment at 195 km", "Hypercharging in 30 minutes", "Feature-packed MoveOS software", "Large 50L under-seat storage"],
    cons: ["Service network still expanding", "Software bugs reported occasionally", "No ABS"],
    metaTitle: "Ola S1 Pro Price in India 2025 – Range, Specs & Review | EV News India",
    metaDescription: "Ola S1 Pro price starts at ₹1,29,999. Range 195 km, top speed 120 km/h. Full specs and hypercharging details.",
    focusKeyword: "Ola S1 Pro price",
    keywords: ["ola s1 pro", "ola electric scooter", "ola s1 pro price", "ola s1 pro range"],
    colors: [{ name: "Jet Black", hexCode: "#1a1a1a", image: "" }, { name: "Porcelain White", hexCode: "#f5f5f0", image: "" }, { name: "Coral Glam", hexCode: "#e8735a", image: "" }, { name: "Sky Blue", hexCode: "#5ab4d6", image: "" }, { name: "Midnight Blue", hexCode: "#1a2a5e", image: "" }],
  },
  {
    name: "Ather 450X Gen 3",
    brand: "Ather Energy",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ather-450x-gen-3",
    status: "published",
    featured: true,
    shortDescription: "Premium performance electric scooter with Warp mode, fast charging, and Ather Grid network.",
    variants: [
      { name: "450X 2.9 kWh", exShowroomPrice: "₹1,29,999", onRoadPrice: "₹1,47,000", batteryCapacity: "2.9 kWh", range: "111 km", availabilityStatus: "Available", features: ["Standard Package"] },
      { name: "450X 3.7 kWh", exShowroomPrice: "₹1,54,999", onRoadPrice: "₹1,75,000", batteryCapacity: "3.7 kWh", range: "150 km", availabilityStatus: "Available", features: ["Warp Mode", "Auto Hold"] },
    ],
    performance: { batteryCapacity: "3.7 kWh", drivingRange: "150 km", power: "6.4 kW", peakPower: "8.8 kW", torque: "26 Nm", topSpeed: "90 km/h", acceleration: "3.3 sec (0–40 km/h)", driveType: "Belt Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "5.45 hrs", dcChargingTime: "1 hr (0–80%)", fastCharging: true, chargingPort: "Ather Dot / Type 2" },
    specs: { length: "1860 mm", width: "695 mm", height: "1150 mm", wheelbase: "1289 mm", groundClearance: "178 mm", kerbWeight: "107 kg", seatingCapacity: "2", tyreType: "Tubeless Radial", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Touchscreen', "Google Maps Navigation", "Ather App"], connectivity: ["Bluetooth 5.0", "Wi-Fi", "4G"], comfort: ["Auto Hold", "Reverse Assist", "27L Storage"], technology: ["OTA Updates", "Ride Statistics", "Warp Mode"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Crash Detection", "Park Assist"] },
    warranty: { vehicle: "3 Years / Unlimited km", battery: "3 Years / 30,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Best-in-class performance with Warp mode", "Excellent build quality", "Strong Ather Grid charging network", "Regular OTA updates"],
    cons: ["Higher price vs competitors", "Limited service centers outside metros", "Smaller under-seat storage"],
    metaTitle: "Ather 450X Gen 3 Price 2025 – Range, Specs & Review | EV News India",
    metaDescription: "Ather 450X Gen 3 price starts at ₹1,29,999. Range up to 150 km, Warp mode. Full specs.",
    focusKeyword: "Ather 450X price",
    keywords: ["ather 450x", "ather 450x gen 3", "ather scooter price"],
    colors: [{ name: "Cosmic Black", hexCode: "#1c1c1c", image: "" }, { name: "Arctic White", hexCode: "#f0f0ec", image: "" }, { name: "Space Grey", hexCode: "#6b7280", image: "" }, { name: "Electric Green", hexCode: "#00c853", image: "" }],
  },
  {
    name: "TVS iQube Electric",
    brand: "TVS Motor",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "tvs-iqube-electric",
    status: "published",
    featured: false,
    shortDescription: "Feature-rich electric scooter by TVS with 5.1 kWh battery and SmartXonnect technology.",
    variants: [
      { name: "iQube S", exShowroomPrice: "₹99,900", onRoadPrice: "₹1,15,000", batteryCapacity: "3.4 kWh", range: "100 km", availabilityStatus: "Available", features: ["Standard"] },
      { name: "iQube ST", exShowroomPrice: "₹1,24,900", onRoadPrice: "₹1,42,000", batteryCapacity: "5.1 kWh", range: "145 km", availabilityStatus: "Available", features: ["Remote Diagnostics", "Glide Through Traffic Mode"] },
    ],
    performance: { batteryCapacity: "5.1 kWh", drivingRange: "145 km", power: "4.4 kW", peakPower: "11 kW", torque: "140 Nm", topSpeed: "82 km/h", acceleration: "4.2 sec (0–40 km/h)", driveType: "Hub Motor", batteryType: "Lithium-Ion" },
    charging: { acChargingTime: "5.5 hrs (0–100%)", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 2" },
    specs: { length: "1791 mm", width: "650 mm", height: "1143 mm", wheelbase: "1275 mm", groundClearance: "155 mm", kerbWeight: "121 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: false, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: true, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['5" TFT Cluster', "SmartXonnect App"], connectivity: ["Bluetooth", "4G"], comfort: ["Glide Through Traffic", "Cruise Control", "Walk Assist"], technology: ["OTA Updates", "Call & SMS Alerts", "Remote Diagnostics"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Theft Alert"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Trusted TVS dealer network", "Highest torque (140 Nm)", "Good real-world range", "Glide-through-traffic mode"],
    cons: ["No fast charging", "Average touchscreen", "Top speed lower than rivals"],
    metaTitle: "TVS iQube Electric Price 2025 – Range, Specs | EV News India",
    metaDescription: "TVS iQube Electric price starts at ₹99,900. Range up to 145 km, 82 km/h top speed.",
    focusKeyword: "TVS iQube price",
    keywords: ["tvs iqube", "tvs electric scooter"],
    colors: [{ name: "Starlight Blue", hexCode: "#4a6fa5", image: "" }, { name: "Autumn Brown", hexCode: "#8B4513", image: "" }, { name: "Pearl White", hexCode: "#f8f8f2", image: "" }, { name: "Matte Black", hexCode: "#2d2d2d", image: "" }],
  },
  {
    name: "Bajaj Chetak Electric",
    brand: "Bajaj Auto",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "bajaj-chetak-electric",
    status: "published",
    featured: false,
    shortDescription: "Iconic retro-styled electric scooter by Bajaj with 108 km range and premium steel body.",
    variants: [
      { name: "Chetak Premium", exShowroomPrice: "₹1,15,000", onRoadPrice: "₹1,30,000", batteryCapacity: "3.2 kWh", range: "108 km", availabilityStatus: "Available", features: ["Steel Body", "IP67 Rating", "Reverse Mode"] },
      { name: "Chetak Premium Plus", exShowroomPrice: "₹1,20,000", onRoadPrice: "₹1,35,000", batteryCapacity: "3.2 kWh", range: "108 km", availabilityStatus: "Available", features: ["Connected Features", "Dark Edition"] },
    ],
    performance: { batteryCapacity: "3.2 kWh", drivingRange: "108 km", power: "3.8 kW", peakPower: "4.5 kW", torque: "16 Nm", topSpeed: "73 km/h", acceleration: "4.5 sec (0–40 km/h)", driveType: "Hub Motor", batteryType: "Lithium-Ion NMC (IP67)" },
    charging: { acChargingTime: "5 hrs (0–100%)", dcChargingTime: "N/A", fastCharging: false, chargingPort: "3-Pin Domestic Socket" },
    specs: { length: "1777 mm", width: "650 mm", height: "1143 mm", wheelbase: "1280 mm", groundClearance: "170 mm", kerbWeight: "129 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: false, instrumentCluster: true, navigation: false, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: false, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ["Digital Instrument Cluster", "LED Display"], connectivity: ["Bluetooth App"], comfort: ["Reverse Mode", "All-Steel Body", "Flat Floorboard"], technology: ["IP67 Waterproof Battery", "Eco & Sport Modes"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "IP67 Battery Protection"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "1 Year" },
    pros: ["Premium retro design with steel body", "IP67 waterproof – ideal for monsoons", "Trusted Bajaj network", "Charge from any domestic socket"],
    cons: ["No fast charging", "Lower range vs rivals", "Higher kerb weight", "No touchscreen"],
    metaTitle: "Bajaj Chetak Electric Price 2025 – Range, Specs | EV News India",
    metaDescription: "Bajaj Chetak Electric price starts at ₹1,15,000. Range 108 km, IP67 waterproof, retro steel body.",
    focusKeyword: "Bajaj Chetak Electric price",
    keywords: ["bajaj chetak electric", "chetak electric price"],
    colors: [{ name: "Brooklands Green", hexCode: "#3a5a40", image: "" }, { name: "Cyber White", hexCode: "#f5f5f5", image: "" }, { name: "Indigo Metallic", hexCode: "#4b0082", image: "" }, { name: "Hazel Beige", hexCode: "#c8a97e", image: "" }],
  },
  {
    name: "Hero Vida V1 Pro",
    brand: "Hero MotoCorp",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "hero-vida-v1-pro",
    status: "published",
    featured: false,
    shortDescription: "Hero's premium electric scooter with 165 km range, removable battery, and fast charging.",
    variants: [
      { name: "Vida V1 Plus", exShowroomPrice: "₹1,14,490", onRoadPrice: "₹1,30,000", batteryCapacity: "3.44 kWh", range: "143 km", availabilityStatus: "Available", features: ["Standard"] },
      { name: "Vida V1 Pro", exShowroomPrice: "₹1,45,780", onRoadPrice: "₹1,65,000", batteryCapacity: "3.94 kWh", range: "165 km", availabilityStatus: "Available", features: ["Fast Charging", "Removable Battery", "Premium Finish"] },
    ],
    performance: { batteryCapacity: "3.94 kWh", drivingRange: "165 km", power: "6 kW", peakPower: "10 kW", torque: "25.9 Nm", topSpeed: "80 km/h", acceleration: "3.8 sec (0–40 km/h)", driveType: "PMSM Hub Motor", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "6 hrs", dcChargingTime: "65 min (0–80%)", fastCharging: true, chargingPort: "Type 2 CCS" },
    specs: { length: "1853 mm", width: "735 mm", height: "1159 mm", wheelbase: "1332 mm", groundClearance: "165 mm", kerbWeight: "136 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Touchscreen', "Vida App", "Navigation"], connectivity: ["Bluetooth", "Wi-Fi", "4G"], comfort: ["Removable Battery", "Reverse Mode", "Walk Assist"], technology: ["OTA Updates", "Geo-Fencing", "Ride Analytics"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Crash Alert", "Theft Alert"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["165 km range – best in class", "Removable battery option", "Large Hero dealer network", "Fast charging supported"],
    cons: ["Heavier at 136 kg", "App connectivity needs improvement", "Higher price for Pro variant"],
    metaTitle: "Hero Vida V1 Pro Price 2025 – Range, Specs | EV News India",
    metaDescription: "Hero Vida V1 Pro price starts at ₹1,45,780. Range 165 km, fast charging, removable battery.",
    focusKeyword: "Hero Vida V1 Pro price",
    keywords: ["hero vida v1 pro", "hero electric scooter", "vida scooter price"],
    colors: [{ name: "Matte Teal", hexCode: "#008080", image: "" }, { name: "Radiant Red", hexCode: "#c0392b", image: "" }, { name: "Pristine White", hexCode: "#fafafa", image: "" }, { name: "Matt Axis Grey", hexCode: "#6c757d", image: "" }],
  },
  {
    name: "Simple One",
    brand: "Simple Energy",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "simple-one",
    status: "published",
    featured: false,
    shortDescription: "India's longest-range electric scooter with 212 km range and innovative frunk storage.",
    variants: [{ name: "Simple One Standard", exShowroomPrice: "₹1,89,999", onRoadPrice: "₹2,10,000", batteryCapacity: "5 kWh", range: "212 km", availabilityStatus: "Available", features: ["Frunk Storage", "Moto Mode", "AI Range Prediction"] }],
    performance: { batteryCapacity: "5 kWh", drivingRange: "212 km", power: "8.5 kW", peakPower: "17.5 kW", torque: "72 Nm", topSpeed: "105 km/h", acceleration: "2.77 sec (0–40 km/h)", driveType: "PMSM Motor", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "2.5 hrs (fast AC)", dcChargingTime: "N/A", fastCharging: true, chargingPort: "Type 2" },
    specs: { length: "1911 mm", width: "714 mm", height: "1167 mm", wheelbase: "1369 mm", groundClearance: "156 mm", kerbWeight: "110 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Touchscreen', "Tyre Pressure Display"], connectivity: ["Bluetooth", "Wi-Fi"], comfort: ["Frunk Storage (12L)", "Reverse Mode", "Walk Assist"], technology: ["AI Range Prediction", "Moto Mode", "OTA Updates"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: true, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Emergency Stop Signal"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Highest range 212 km in India", "Frunk storage – unique innovation", "Excellent peak power 17.5 kW", "Fastest acceleration in segment", "Lightweight at 110 kg"],
    cons: ["Limited service network", "Brand relatively new", "Expensive vs rivals"],
    metaTitle: "Simple One Price 2025 – 212 km Range Electric Scooter | EV News India",
    metaDescription: "Simple One price ₹1,89,999. India's longest range electric scooter at 212 km. Frunk storage, 105 km/h.",
    focusKeyword: "Simple One electric scooter price",
    keywords: ["simple one", "simple energy scooter", "simple one price"],
    colors: [{ name: "Brazen Black", hexCode: "#1a1a1a", image: "" }, { name: "Namma Red", hexCode: "#b22222", image: "" }, { name: "Arctic Blue", hexCode: "#4a90d9", image: "" }, { name: "Navarasa Gold", hexCode: "#d4af37", image: "" }],
  },
  {
    name: "Ather Rizta",
    brand: "Ather Energy",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ather-rizta",
    status: "published",
    featured: false,
    shortDescription: "Ather's family-friendly electric scooter with the largest seat and highest comfort in the segment.",
    variants: [
      { name: "Rizta S 2.9 kWh", exShowroomPrice: "₹1,09,999", onRoadPrice: "₹1,28,000", batteryCapacity: "2.9 kWh", range: "123 km", availabilityStatus: "Available", features: ["Standard"] },
      { name: "Rizta Z 3.7 kWh", exShowroomPrice: "₹1,29,999", onRoadPrice: "₹1,50,000", batteryCapacity: "3.7 kWh", range: "159 km", availabilityStatus: "Available", features: ["Auto Hold", "Family Mode"] },
    ],
    performance: { batteryCapacity: "3.7 kWh", drivingRange: "159 km", power: "6 kW", peakPower: "8.5 kW", torque: "26 Nm", topSpeed: "80 km/h", acceleration: "4.0 sec (0–40 km/h)", driveType: "Belt Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "5.5 hrs", dcChargingTime: "1 hr (0–80%)", fastCharging: true, chargingPort: "Ather Dot / Type 2" },
    specs: { length: "1900 mm", width: "730 mm", height: "1200 mm", wheelbase: "1320 mm", groundClearance: "178 mm", kerbWeight: "111 kg", seatingCapacity: "2", tyreType: "Tubeless Radial", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Display', "Google Maps Navigation"], connectivity: ["Bluetooth 5.0", "Wi-Fi", "4G"], comfort: ["Extra-Wide Seat", "Family Mode", "Auto Hold", "33L Storage"], technology: ["OTA Updates", "Crash Detection", "Family Safety Alerts"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Family Ride Alerts"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 30,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Widest seat in segment", "Family-friendly riding modes", "Excellent ground clearance (178 mm)", "Ather Grid charging network"],
    cons: ["Not sporty – comfort focused", "No Warp mode", "Limited boot space"],
    metaTitle: "Ather Rizta Price 2025 – Range, Specs | EV News India",
    metaDescription: "Ather Rizta price starts at ₹1,09,999. Range 159 km, family-friendly, 178 mm ground clearance.",
    focusKeyword: "Ather Rizta price",
    keywords: ["ather rizta", "ather rizta price", "ather family scooter"],
    colors: [{ name: "Lunar Silver", hexCode: "#c0c0c0", image: "" }, { name: "Stellar Black", hexCode: "#1c1c1c", image: "" }, { name: "Aurora Green", hexCode: "#2ecc71", image: "" }, { name: "Nova White", hexCode: "#f5f5f5", image: "" }],
  },
  {
    name: "Revolt RV400 BRZ",
    brand: "Revolt Motors",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "revolt-rv400-brz",
    status: "published",
    featured: false,
    shortDescription: "India's first AI-enabled electric motorcycle with artificial exhaust sound and 150 km range.",
    variants: [{ name: "RV400 BRZ", exShowroomPrice: "₹1,38,000", onRoadPrice: "₹1,58,000", batteryCapacity: "3.24 kWh", range: "150 km", availabilityStatus: "Available", features: ["Artificial Sound", "My Revolt App", "ABS"] }],
    performance: { batteryCapacity: "3.24 kWh", drivingRange: "150 km", power: "3 kW", peakPower: "5 kW", torque: "170 Nm", topSpeed: "85 km/h", acceleration: "5.9 sec (0–60 km/h)", driveType: "Chain Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "4.5 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 1" },
    specs: { length: "2010 mm", width: "800 mm", height: "1090 mm", wheelbase: "1335 mm", groundClearance: "215 mm", kerbWeight: "108 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "17 inch Alloy" },
    keyFeatures: { touchscreen: false, instrumentCluster: true, navigation: false, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ["Digital Cluster", "My Revolt App"], connectivity: ["Bluetooth", "4G SIM"], comfort: ["Artificial Exhaust Sound", "Switchable Modes"], technology: ["OTA Updates", "AI Route Optimisation", "Geo-Fencing"] },
    safety: { airbags: "N/A", abs: true, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["ABS", "Theft Alarm"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 40,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Only affordable electric motorcycle", "ABS standard", "Excellent ground clearance (215 mm)", "Artificial exhaust sound – unique"],
    cons: ["No fast charging", "Limited service network", "Subscription model"],
    metaTitle: "Revolt RV400 BRZ Price 2025 – Electric Motorcycle | EV News India",
    metaDescription: "Revolt RV400 BRZ price ₹1,38,000. Electric motorcycle 150 km range, ABS, artificial sound.",
    focusKeyword: "Revolt RV400 price",
    keywords: ["revolt rv400", "revolt electric motorcycle"],
    colors: [{ name: "Rebel Red", hexCode: "#c0392b", image: "" }, { name: "Midnight Black", hexCode: "#1a1a1a", image: "" }, { name: "Pearl White", hexCode: "#f0f0f0", image: "" }],
  },
  {
    name: "Ultraviolette F77 Mach 2",
    brand: "Ultraviolette",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ultraviolette-f77-mach-2",
    status: "published",
    featured: true,
    shortDescription: "India's most powerful electric motorcycle with 323 km range, 0–60 in 2.9 sec.",
    variants: [
      { name: "F77 Mach 2 Standard", exShowroomPrice: "₹3,80,000", onRoadPrice: "₹4,30,000", batteryCapacity: "10.3 kWh", range: "323 km", availabilityStatus: "Available", features: ["Track Mode", "Cloud Connectivity"] },
      { name: "F77 Mach 2 Laser", exShowroomPrice: "₹4,55,000", onRoadPrice: "₹5,10,000", batteryCapacity: "10.3 kWh", range: "323 km", availabilityStatus: "Available", features: ["Laser Headlight", "Aero Kit", "Carbon Fibre"] },
    ],
    performance: { batteryCapacity: "10.3 kWh", drivingRange: "323 km", power: "25 kW", peakPower: "36 kW", torque: "100 Nm", topSpeed: "152 km/h", acceleration: "2.9 sec (0–60 km/h)", driveType: "Chain Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "5 hrs", dcChargingTime: "1.5 hrs (0–80%)", fastCharging: true, chargingPort: "CCS2" },
    specs: { length: "2040 mm", width: "790 mm", height: "1080 mm", wheelbase: "1380 mm", groundClearance: "176 mm", kerbWeight: "207 kg", seatingCapacity: "2", tyreType: "Pirelli Diablo Rosso IV", wheelSize: "17 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: true, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Display', "UV Cloud App", "Ride Analytics"], connectivity: ["Bluetooth", "4G LTE", "Wi-Fi"], comfort: ["Adjustable Suspension", "Multiple Modes", "Cruise Control"], technology: ["Track Mode", "Lean Angle Sensor", "Regen Braking"] },
    safety: { airbags: "N/A", abs: true, ebd: true, esc: false, tractionControl: true, tpms: true, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: ["Traction Control", "Cornering ABS"], safetyRating: "N/A", additionalEquipment: ["Cornering ABS", "Pirelli Tyres"] },
    warranty: { vehicle: "2 Years", battery: "2 Years / 40,000 km", motor: "2 Years", roadsideAssistance: "2 Years" },
    pros: ["India's most powerful e-motorcycle", "323 km range", "0–60 in 2.9 seconds", "152 km/h top speed", "Cornering ABS + traction control"],
    cons: ["Very expensive ₹3.8 Lakh+", "Heavy at 207 kg", "Very limited service network"],
    metaTitle: "Ultraviolette F77 Mach 2 Price 2025 – 323 km Range | EV News India",
    metaDescription: "Ultraviolette F77 Mach 2 price ₹3,80,000. 323 km range, 152 km/h top speed, 36 kW peak power.",
    focusKeyword: "Ultraviolette F77 Mach 2 price",
    keywords: ["ultraviolette f77", "uv f77 mach 2", "ultraviolette electric motorcycle"],
    colors: [{ name: "Airstrike Black", hexCode: "#1a1a1a", image: "" }, { name: "Laser Beam White", hexCode: "#f5f5f5", image: "" }, { name: "Shadow Red", hexCode: "#8b0000", image: "" }, { name: "Ion Blue", hexCode: "#1e90ff", image: "" }],
  },
  {
    name: "Tork Kratos R",
    brand: "Tork Motors",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "tork-kratos-r",
    status: "published",
    featured: false,
    shortDescription: "Affordable electric motorcycle with 180 km range, 105 km/h top speed and sports styling.",
    variants: [
      { name: "Kratos", exShowroomPrice: "₹1,29,999", onRoadPrice: "₹1,48,000", batteryCapacity: "4 kWh", range: "120 km", availabilityStatus: "Available", features: ["Standard"] },
      { name: "Kratos R", exShowroomPrice: "₹1,59,999", onRoadPrice: "₹1,80,000", batteryCapacity: "4 kWh", range: "180 km", availabilityStatus: "Available", features: ["ABS", "Extended Range", "Connected"] },
    ],
    performance: { batteryCapacity: "4 kWh", drivingRange: "180 km", power: "7.5 kW", peakPower: "9 kW", torque: "38 Nm", topSpeed: "105 km/h", acceleration: "3.4 sec (0–40 km/h)", driveType: "Belt Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "4 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 1" },
    specs: { length: "2050 mm", width: "820 mm", height: "1090 mm", wheelbase: "1360 mm", groundClearance: "175 mm", kerbWeight: "125 kg", seatingCapacity: "2", tyreType: "MRF Tubeless", wheelSize: "17 inch Alloy" },
    keyFeatures: { touchscreen: false, instrumentCluster: true, navigation: false, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ["Digital Cluster", "Tork App"], connectivity: ["Bluetooth", "SIM Connectivity"], comfort: ["Eco / City / Storm Modes", "Regenerative Braking"], technology: ["OTA Updates", "Geo-Fencing", "Lean Angle Monitoring"] },
    safety: { airbags: "N/A", abs: true, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["ABS (Kratos R)", "Anti-Theft Alarm"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "2 Years" },
    pros: ["ABS standard on Kratos R", "Sports design", "Good 180 km range", "Affordable pricing"],
    cons: ["Very limited service network", "No fast charging", "App needs improvement"],
    metaTitle: "Tork Kratos R Price 2025 – 180 km Electric Motorcycle | EV News India",
    metaDescription: "Tork Kratos R price ₹1,59,999. 180 km range, 105 km/h top speed, ABS standard.",
    focusKeyword: "Tork Kratos R price",
    keywords: ["tork kratos r", "tork electric motorcycle"],
    colors: [{ name: "Molten Black", hexCode: "#1a1a1a", image: "" }, { name: "Metallic Blue", hexCode: "#1a3a8f", image: "" }, { name: "Racing Red", hexCode: "#b00020", image: "" }],
  },
  {
    name: "Matter Aera",
    brand: "Matter",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "matter-aera",
    status: "published",
    featured: false,
    shortDescription: "World's first electric motorcycle with 4-speed MTRX gearbox and 200 km range.",
    variants: [
      { name: "Aera 5000", exShowroomPrice: "₹1,88,999", onRoadPrice: "₹2,15,000", batteryCapacity: "5 kWh", range: "200 km", availabilityStatus: "Available", features: ["MTRX Gearbox", "ABS"] },
      { name: "Aera 5000+", exShowroomPrice: "₹2,06,000", onRoadPrice: "₹2,33,000", batteryCapacity: "5 kWh", range: "200 km", availabilityStatus: "Available", features: ["MTRX Gearbox", "ABS", "TFT Display", "Connected"] },
    ],
    performance: { batteryCapacity: "5 kWh", drivingRange: "200 km", power: "10 kW", peakPower: "12.5 kW", torque: "520 Nm", topSpeed: "125 km/h", acceleration: "4.5 sec (0–60 km/h)", driveType: "MTRX 4-Speed Geared", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "5 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 1" },
    specs: { length: "2148 mm", width: "825 mm", height: "1110 mm", wheelbase: "1440 mm", groundClearance: "195 mm", kerbWeight: "132 kg", seatingCapacity: "2", tyreType: "MRF Tubeless", wheelSize: "17 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ["TFT Display", "Matter App"], connectivity: ["Bluetooth", "4G"], comfort: ["4-Speed MTRX Gearbox", "Gear Indicator", "Multiple Modes"], technology: ["OTA Updates", "Regen Braking", "Engine Braking"] },
    safety: { airbags: "N/A", abs: true, ebd: true, esc: false, tractionControl: false, tpms: false, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["ABS with EBD", "Disc Brakes F&R"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "2 Years" },
    pros: ["World's first geared electric motorcycle", "Familiar ICE experience", "200 km range", "195 mm ground clearance", "ABS + EBD"],
    cons: ["Very limited service network", "Expensive", "Gearbox adds complexity"],
    metaTitle: "Matter Aera Price 2025 – Geared Electric Motorcycle | EV News India",
    metaDescription: "Matter Aera price ₹1,88,999. World's first 4-speed geared electric motorcycle. 200 km range.",
    focusKeyword: "Matter Aera price",
    keywords: ["matter aera", "matter electric motorcycle", "geared electric bike"],
    colors: [{ name: "Stealth Black", hexCode: "#1a1a1a", image: "" }, { name: "Alpine White", hexCode: "#f5f5f5", image: "" }, { name: "Phantom Blue", hexCode: "#1c3a5e", image: "" }],
  },
  {
    name: "Ola S1 X",
    brand: "Ola Electric",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ola-s1-x",
    status: "published",
    featured: false,
    shortDescription: "Ola's most affordable electric scooter starting at ₹79,999 with up to 151 km range.",
    variants: [
      { name: "S1 X 2 kWh", exShowroomPrice: "₹79,999", onRoadPrice: "₹93,000", batteryCapacity: "2 kWh", range: "91 km", availabilityStatus: "Available", features: ["Basic"] },
      { name: "S1 X 3 kWh", exShowroomPrice: "₹99,999", onRoadPrice: "₹1,15,000", batteryCapacity: "3 kWh", range: "131 km", availabilityStatus: "Available", features: ["MoveOS Lite"] },
      { name: "S1 X 4 kWh", exShowroomPrice: "₹1,09,999", onRoadPrice: "₹1,26,000", batteryCapacity: "4 kWh", range: "151 km", availabilityStatus: "Available", features: ["MoveOS Full", "Touchscreen", "Navigation"] },
    ],
    performance: { batteryCapacity: "4 kWh", drivingRange: "151 km", power: "6 kW", peakPower: "8 kW", torque: "48 Nm", topSpeed: "90 km/h", acceleration: "4.5 sec (0–40 km/h)", driveType: "Rear Hub Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "7 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 2" },
    specs: { length: "1836 mm", width: "710 mm", height: "1148 mm", wheelbase: "1330 mm", groundClearance: "165 mm", kerbWeight: "112 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" Touchscreen (4 kWh)', "MoveOS Lite/Full"], connectivity: ["Bluetooth", "Wi-Fi (4 kWh)"], comfort: ["Hill Hold", "38L Storage"], technology: ["OTA Updates", "Ride Modes"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Find My Scooter"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Most affordable Ola at ₹79,999", "Three battery options", "Good range up to 151 km", "MoveOS ecosystem"],
    cons: ["No fast charging", "Base variant very basic", "Service network concerns"],
    metaTitle: "Ola S1 X Price 2025 – ₹79,999 Electric Scooter | EV News India",
    metaDescription: "Ola S1 X price starts ₹79,999. Range up to 151 km, 3 battery options. Most affordable Ola scooter.",
    focusKeyword: "Ola S1 X price",
    keywords: ["ola s1 x", "ola electric scooter price", "affordable electric scooter india"],
    colors: [{ name: "Jet Black", hexCode: "#1a1a1a", image: "" }, { name: "Pearl White", hexCode: "#f5f5f5", image: "" }, { name: "Liquid Silver", hexCode: "#c0c0c0", image: "" }, { name: "Midnight Blue", hexCode: "#191970", image: "" }, { name: "Coral Glam", hexCode: "#e8735a", image: "" }],
  },
  {
    name: "Ather 450S",
    brand: "Ather Energy",
    vehicleType: "bike",
    category: "popular",
    availability: "available",
    slug: "ather-450s",
    status: "published",
    featured: false,
    shortDescription: "The more affordable sibling of 450X with smart features and 115 km range.",
    variants: [{ name: "450S 2.9 kWh", exShowroomPrice: "₹1,09,999", onRoadPrice: "₹1,28,000", batteryCapacity: "2.9 kWh", range: "115 km", availabilityStatus: "Available", features: ["Dashboard", "Navigation", "Ather App"] }],
    performance: { batteryCapacity: "2.9 kWh", drivingRange: "115 km", power: "5.4 kW", peakPower: "7 kW", torque: "22 Nm", topSpeed: "80 km/h", acceleration: "3.9 sec (0–40 km/h)", driveType: "Belt Drive", batteryType: "Lithium-Ion NMC" },
    charging: { acChargingTime: "5.45 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "Type 2" },
    specs: { length: "1860 mm", width: "695 mm", height: "1150 mm", wheelbase: "1289 mm", groundClearance: "178 mm", kerbWeight: "107 kg", seatingCapacity: "2", tyreType: "Tubeless Radial", wheelSize: "12 inch" },
    keyFeatures: { touchscreen: true, instrumentCluster: true, navigation: true, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: true, cruiseControl: false, keylessEntry: true, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ['7" TFT Display', "Google Maps Navigation"], connectivity: ["Bluetooth 5.0", "Wi-Fi"], comfort: ["Auto Hold", "Park Assist", "Walk Mode"], technology: ["OTA Updates", "Crash Detection", "Trip Analytics"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: true, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS", "Crash Detection"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 30,000 km", motor: "3 Years", roadsideAssistance: "3 Years" },
    pros: ["Ather quality at lower price", "Smart navigation + OTA", "Ather Grid access", "Keyless entry", "Great ground clearance (178 mm)"],
    cons: ["No fast charging", "Smaller battery than 450X", "No Warp mode"],
    metaTitle: "Ather 450S Price 2025 – Range, Specs | EV News India",
    metaDescription: "Ather 450S price ₹1,09,999. Range 115 km, 80 km/h top speed. Affordable Ather with smart features.",
    focusKeyword: "Ather 450S price",
    keywords: ["ather 450s", "ather 450s price"],
    colors: [{ name: "Cosmic Black", hexCode: "#1c1c1c", image: "" }, { name: "Arctic White", hexCode: "#f0f0ec", image: "" }, { name: "Space Grey", hexCode: "#6b7280", image: "" }],
  },
  {
    name: "Bajaj Chetak 35 Series",
    brand: "Bajaj Auto",
    vehicleType: "bike",
    category: "upcoming",
    availability: "upcoming",
    slug: "bajaj-chetak-35-series",
    status: "published",
    featured: false,
    launchDate: new Date("2025-10-01"),
    shortDescription: "Next-gen Chetak with improved connectivity, updated design, and better range.",
    variants: [{ name: "Chetak 35 Standard", exShowroomPrice: "₹1,15,000", onRoadPrice: "₹1,32,000", batteryCapacity: "3.2 kWh", range: "108 km", availabilityStatus: "Upcoming", features: ["Bluetooth Connectivity", "IP67 Battery"] }],
    performance: { batteryCapacity: "3.2 kWh", drivingRange: "108 km", power: "3.8 kW", peakPower: "4.5 kW", torque: "16 Nm", topSpeed: "73 km/h", acceleration: "4.5 sec (0–40 km/h)", driveType: "Hub Motor", batteryType: "Lithium-Ion NMC (IP67)" },
    charging: { acChargingTime: "5 hrs", dcChargingTime: "N/A", fastCharging: false, chargingPort: "3-Pin Domestic" },
    specs: { length: "1780 mm", width: "650 mm", height: "1145 mm", wheelbase: "1282 mm", groundClearance: "170 mm", kerbWeight: "129 kg", seatingCapacity: "2", tyreType: "Tubeless", wheelSize: "12 inch Alloy" },
    keyFeatures: { touchscreen: false, instrumentCluster: true, navigation: false, bluetooth: true, androidAuto: false, appleCarPlay: false, otaUpdates: false, cruiseControl: false, keylessEntry: false, sunroof: false, ventilatedSeats: false, wirelessCharging: false },
    features: { infotainment: ["Updated Digital Cluster"], connectivity: ["Bluetooth App"], comfort: ["Reverse Mode", "Steel Body"], technology: ["IP67 Battery", "Eco & Sport Modes"] },
    safety: { airbags: "N/A", abs: false, ebd: false, esc: false, tractionControl: false, tpms: false, hillHoldAssist: false, reverseCamera: false, parkingSensors: false, adasFeatures: [], safetyRating: "N/A", additionalEquipment: ["CBS"] },
    warranty: { vehicle: "3 Years", battery: "3 Years / 50,000 km", motor: "3 Years", roadsideAssistance: "1 Year" },
    pros: ["Iconic Bajaj design", "Reliable nationwide network", "IP67 waterproofing"],
    cons: ["No fast charging", "Limited range", "No touchscreen"],
    metaTitle: "Bajaj Chetak 35 Series Price 2025 – Upcoming | EV News India",
    metaDescription: "Bajaj Chetak 35 Series expected price ₹1,15,000. Upcoming 2025 with improved Bluetooth and range.",
    focusKeyword: "Bajaj Chetak 35 Series",
    keywords: ["bajaj chetak 35", "new chetak 2025", "chetak electric upcoming"],
    colors: [{ name: "Cyber White", hexCode: "#f5f5f5", image: "" }, { name: "Indigo Metallic", hexCode: "#4b0082", image: "" }, { name: "Matte Black", hexCode: "#2d2d2d", image: "" }],
  },
];

/* ─── Main ──────────────────────────────────────────────────────────── */
async function main() {
  const client = new MongoClient(MONGODB_URI);
  try {
    await client.connect();
    console.log("✓ Connected to MongoDB");

    const db  = client.db(DB_NAME);
    const col = db.collection("vehicles");

    let inserted = 0, updated = 0, failed = 0;

    for (const bike of bikes) {
      try {
        const result = await col.updateOne(
          { slug: bike.slug },
          { $set: { ...bike, updatedAt: new Date() }, $setOnInsert: { createdAt: new Date(), views: 0 } },
          { upsert: true }
        );
        if (result.upsertedCount > 0) { inserted++; console.log(`  ✓ Inserted: ${bike.name}`); }
        else if (result.modifiedCount > 0) { updated++; console.log(`  ↻ Updated:  ${bike.name}`); }
        else { console.log(`  = Unchanged: ${bike.name}`); }
      } catch (err) {
        failed++;
        console.error(`  ✗ Failed:  ${bike.name} — ${err.message}`);
      }
    }

    console.log(`\n╔══════════════════════════════════╗`);
    console.log(`║  SEED COMPLETE                   ║`);
    console.log(`║  Total:    ${String(bikes.length).padEnd(23)}║`);
    console.log(`║  Inserted: ${String(inserted).padEnd(23)}║`);
    console.log(`║  Updated:  ${String(updated).padEnd(23)}║`);
    console.log(`║  Failed:   ${String(failed).padEnd(23)}║`);
    console.log(`╚══════════════════════════════════╝`);

    const verify = await col.countDocuments({ vehicleType: "bike" });
    console.log(`\n  Total electric bikes in DB: ${verify}`);
  } finally {
    await client.close();
  }
}

main().catch(console.error);
